const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const collegesData = [
  {
    name: 'IIT Bombay',
    location: 'Mumbai, Maharashtra',
    fees: 200000,
    rating: 4.8,
    placements: 95,
    description: 'One of the premier engineering institutes in India, IIT Bombay is known for its rigorous curriculum and top-notch faculty.',
    courses: [
      { name: 'Computer Science and Engineering', duration: '4 years', fees: 50000 },
      { name: 'Mechanical Engineering', duration: '4 years', fees: 50000 },
      { name: 'Electrical Engineering', duration: '4 years', fees: 50000 },
    ],
  },
  {
    name: 'IIT Delhi',
    location: 'Delhi, Delhi',
    fees: 180000,
    rating: 4.75,
    placements: 94,
    description: 'IIT Delhi is a leading institute offering world-class engineering education with strong industry connections.',
    courses: [
      { name: 'Electronics and Communication', duration: '4 years', fees: 45000 },
      { name: 'Civil Engineering', duration: '4 years', fees: 45000 },
      { name: 'Chemical Engineering', duration: '4 years', fees: 45000 },
    ],
  },
  {
    name: 'NIT Trichy',
    location: 'Tiruchirappalli, Tamil Nadu',
    fees: 120000,
    rating: 4.5,
    placements: 92,
    description: 'NIT Trichy is a prestigious National Institute of Technology with excellent placement records.',
    courses: [
      { name: 'Computer Science', duration: '4 years', fees: 30000 },
      { name: 'Electronics Engineering', duration: '4 years', fees: 30000 },
      { name: 'Production Engineering', duration: '4 years', fees: 30000 },
    ],
  },
  {
    name: 'BITS Pilani',
    location: 'Pilani, Rajasthan',
    fees: 350000,
    rating: 4.7,
    placements: 96,
    description: 'BITS Pilani is a private institution known for quality education and excellent global placements.',
    courses: [
      { name: 'Computer Science', duration: '4 years', fees: 87500 },
      { name: 'Electronics and Instrumentation', duration: '4 years', fees: 87500 },
      { name: 'Mechanical Engineering', duration: '4 years', fees: 87500 },
    ],
  },
  {
    name: 'VIT Vellore',
    location: 'Vellore, Tamil Nadu',
    fees: 250000,
    rating: 4.4,
    placements: 90,
    description: 'VIT is a leading private university with strong emphasis on research and innovation.',
    courses: [
      { name: 'Computer Science Engineering', duration: '4 years', fees: 62500 },
      { name: 'Electrical and Electronics', duration: '4 years', fees: 62500 },
      { name: 'Mechanical Engineering', duration: '4 years', fees: 62500 },
    ],
  },
  {
    name: 'MIT Pune',
    location: 'Pune, Maharashtra',
    fees: 220000,
    rating: 4.3,
    placements: 88,
    description: 'MIT Pune offers quality engineering education with modern infrastructure and skilled faculty.',
    courses: [
      { name: 'Computer Science', duration: '4 years', fees: 55000 },
      { name: 'Information Technology', duration: '4 years', fees: 55000 },
      { name: 'Mechanical Engineering', duration: '4 years', fees: 55000 },
    ],
  },
  {
    name: 'Anna University',
    location: 'Chennai, Tamil Nadu',
    fees: 100000,
    rating: 4.2,
    placements: 85,
    description: 'Anna University is a major institution in south India with strong technical programs.',
    courses: [
      { name: 'Computer Science and Engineering', duration: '4 years', fees: 25000 },
      { name: 'Civil Engineering', duration: '4 years', fees: 25000 },
      { name: 'Electrical Engineering', duration: '4 years', fees: 25000 },
    ],
  },
  {
    name: 'Delhi Technological University',
    location: 'Delhi, Delhi',
    fees: 110000,
    rating: 4.3,
    placements: 87,
    description: 'DTU is a leading engineering institution in New Delhi with excellent academic programs.',
    courses: [
      { name: 'Computer Engineering', duration: '4 years', fees: 27500 },
      { name: 'Electronics and Communication', duration: '4 years', fees: 27500 },
      { name: 'Biotechnology', duration: '4 years', fees: 27500 },
    ],
  },
  {
    name: 'Manipal Institute of Technology',
    location: 'Manipal, Karnataka',
    fees: 280000,
    rating: 4.5,
    placements: 91,
    description: 'MIT Manipal is known for its global exposure and research-focused curriculum.',
    courses: [
      { name: 'Computer and Information Technology', duration: '4 years', fees: 70000 },
      { name: 'Aerospace Engineering', duration: '4 years', fees: 70000 },
      { name: 'Mechanical Engineering', duration: '4 years', fees: 70000 },
    ],
  },
  {
    name: 'Jadavpur University',
    location: 'Kolkata, West Bengal',
    fees: 95000,
    rating: 4.1,
    placements: 83,
    description: 'Jadavpur University is a premier institution in eastern India with strong engineering programs.',
    courses: [
      { name: 'Computer Science and Engineering', duration: '4 years', fees: 23750 },
      { name: 'Electronics and Electrical Communication', duration: '4 years', fees: 23750 },
      { name: 'Mechanical Engineering', duration: '4 years', fees: 23750 },
    ],
  },
  {
    name: 'SRM Institute of Science and Technology',
    location: 'Chennai, Tamil Nadu',
    fees: 240000,
    rating: 4.3,
    placements: 89,
    description: 'SRM IST is a leading private institution with excellent infrastructure and placement opportunities.',
    courses: [
      { name: 'Computer Science and Engineering', duration: '4 years', fees: 60000 },
      { name: 'Information Technology', duration: '4 years', fees: 60000 },
      { name: 'Electronics and Communication', duration: '4 years', fees: 60000 },
    ],
  },
  {
    name: 'Amrita Vishwa Vidyapeetham',
    location: 'Coimbatore, Tamil Nadu',
    fees: 260000,
    rating: 4.4,
    placements: 89,
    description: 'Amrita is a highly ranked institution with strong values and excellent academic rigor.',
    courses: [
      { name: 'Computer Science and Engineering', duration: '4 years', fees: 65000 },
      { name: 'Electronics and Communication', duration: '4 years', fees: 65000 },
      { name: 'Mechanical Engineering', duration: '4 years', fees: 65000 },
    ],
  },
  {
    name: 'IIT Madras',
    location: 'Chennai, Tamil Nadu',
    fees: 210000,
    rating: 4.9,
    placements: 97,
    description: 'Consistently ranked as the top engineering institute in India, IIT Madras excels in research and placements.',
    courses: [
      { name: 'Aerospace Engineering', duration: '4 years', fees: 52500 },
      { name: 'Computer Science', duration: '4 years', fees: 52500 },
      { name: 'Electrical Engineering', duration: '4 years', fees: 52500 },
    ],
  },
  {
    name: 'IIT Kharagpur',
    location: 'Kharagpur, West Bengal',
    fees: 195000,
    rating: 4.7,
    placements: 93,
    description: 'The oldest IIT in the country, featuring a vast campus and extensive engineering programs.',
    courses: [
      { name: 'Computer Science and Engineering', duration: '4 years', fees: 48750 },
      { name: 'Agricultural Engineering', duration: '4 years', fees: 48750 },
      { name: 'Mining Engineering', duration: '4 years', fees: 48750 },
    ],
  },
  {
    name: 'IIT Kanpur',
    location: 'Kanpur, Uttar Pradesh',
    fees: 205000,
    rating: 4.75,
    placements: 94,
    description: 'IIT Kanpur is renowned for its science-focused engineering curriculum and robust computing facilities.',
    courses: [
      { name: 'Computer Science', duration: '4 years', fees: 51250 },
      { name: 'Materials Science', duration: '4 years', fees: 51250 },
      { name: 'Aerospace Engineering', duration: '4 years', fees: 51250 },
    ],
  },
  {
    name: 'IIT Roorkee',
    location: 'Roorkee, Uttarakhand',
    fees: 190000,
    rating: 4.65,
    placements: 91,
    description: 'Originating as Thomason College of Civil Engineering, IIT Roorkee is India\'s oldest technical institution.',
    courses: [
      { name: 'Civil Engineering', duration: '4 years', fees: 47500 },
      { name: 'Computer Science', duration: '4 years', fees: 47500 },
      { name: 'Electrical Engineering', duration: '4 years', fees: 47500 },
    ],
  },
  {
    name: 'IIT Guwahati',
    location: 'Guwahati, Assam',
    fees: 185000,
    rating: 4.6,
    placements: 90,
    description: 'Located on the banks of the Brahmaputra, IIT Guwahati offers scenic beauty alongside academic excellence.',
    courses: [
      { name: 'Computer Science', duration: '4 years', fees: 46250 },
      { name: 'Data Science', duration: '4 years', fees: 46250 },
      { name: 'Design Engineering', duration: '4 years', fees: 46250 },
    ],
  },
  {
    name: 'IIT Hyderabad',
    location: 'Hyderabad, Telangana',
    fees: 215000,
    rating: 4.65,
    placements: 92,
    description: 'A fast-growing new generation IIT with strong research collaborations with Japanese universities.',
    courses: [
      { name: 'Artificial Intelligence', duration: '4 years', fees: 53750 },
      { name: 'Computer Science', duration: '4 years', fees: 53750 },
      { name: 'Biomedical Engineering', duration: '4 years', fees: 53750 },
    ],
  },
  {
    name: 'NIT Surathkal',
    location: 'Mangaluru, Karnataka',
    fees: 135000,
    rating: 4.55,
    placements: 93,
    description: 'Situated next to the Arabian Sea, NIT Surathkal is a premier technical institute with great campus life.',
    courses: [
      { name: 'Information Technology', duration: '4 years', fees: 33750 },
      { name: 'Computer Science', duration: '4 years', fees: 33750 },
      { name: 'Mining Engineering', duration: '4 years', fees: 33750 },
    ],
  },
  {
    name: 'NIT Rourkela',
    location: 'Rourkela, Odisha',
    fees: 125000,
    rating: 4.45,
    placements: 89,
    description: 'One of the largest NIT campuses, NIT Rourkela is known for its diverse student body and core engineering branches.',
    courses: [
      { name: 'Metallurgical Engineering', duration: '4 years', fees: 31250 },
      { name: 'Computer Science', duration: '4 years', fees: 31250 },
      { name: 'Ceramic Engineering', duration: '4 years', fees: 31250 },
    ],
  },
  {
    name: 'NIT Warangal',
    location: 'Warangal, Telangana',
    fees: 130000,
    rating: 4.5,
    placements: 91,
    description: 'The first NIT ever established in the country, famed for its strong academic foundation.',
    courses: [
      { name: 'Computer Science and Engineering', duration: '4 years', fees: 32500 },
      { name: 'Electronics and Communication', duration: '4 years', fees: 32500 },
      { name: 'Civil Engineering', duration: '4 years', fees: 32500 },
    ],
  },
  {
    name: 'IIIT Hyderabad',
    location: 'Hyderabad, Telangana',
    fees: 300000,
    rating: 4.75,
    placements: 98,
    description: 'An independent research university focused on Information Technology, offering unmatched computer science placements.',
    courses: [
      { name: 'Computer Science', duration: '4 years', fees: 75000 },
      { name: 'Electronics and Communication', duration: '4 years', fees: 75000 },
      { name: 'Computational Linguistics', duration: '4 years', fees: 75000 },
    ],
  },
  {
    name: 'IIIT Bangalore',
    location: 'Bangalore, Karnataka',
    fees: 320000,
    rating: 4.6,
    placements: 97,
    description: 'Located in the IT capital of India, IIIT Bangalore offers highly industry-aligned curriculum.',
    courses: [
      { name: 'Computer Science', duration: '4 years', fees: 80000 },
      { name: 'Data Science', duration: '4 years', fees: 80000 },
      { name: 'Electronic Systems', duration: '4 years', fees: 80000 },
    ],
  },
  {
    name: 'IIIT Allahabad',
    location: 'Allahabad, Uttar Pradesh',
    fees: 160000,
    rating: 4.5,
    placements: 94,
    description: 'A key institute of information technology with specialization in IT, robotics, and wireless communications.',
    courses: [
      { name: 'Information Technology', duration: '4 years', fees: 40000 },
      { name: 'Electronics and Communication', duration: '4 years', fees: 40000 },
      { name: 'Business Informatics', duration: '4 years', fees: 40000 },
    ],
  },
  {
    name: 'BITS Hyderabad',
    location: 'Hyderabad, Telangana',
    fees: 340000,
    rating: 4.6,
    placements: 95,
    description: 'A state-of-the-art campus of BITS Pilani, offering quality engineering and sciences education.',
    courses: [
      { name: 'Computer Science', duration: '4 years', fees: 85000 },
      { name: 'Chemical Engineering', duration: '4 years', fees: 85000 },
      { name: 'Electrical Engineering', duration: '4 years', fees: 85000 },
    ],
  },
  {
    name: 'BITS Goa',
    location: 'Vasco da Gama, Goa',
    fees: 340000,
    rating: 4.65,
    placements: 95,
    description: 'Set in a scenic location in Goa, BITS Goa combines excellent academics with a vibrant culture.',
    courses: [
      { name: 'Computer Science', duration: '4 years', fees: 85000 },
      { name: 'Electronics and Communication', duration: '4 years', fees: 85000 },
      { name: 'Mechanical Engineering', duration: '4 years', fees: 85000 },
    ],
  },
  {
    name: 'COEP Pune',
    location: 'Pune, Maharashtra',
    fees: 115000,
    rating: 4.4,
    placements: 89,
    description: 'College of Engineering Pune is one of the oldest engineering colleges in Asia, possessing a rich heritage.',
    courses: [
      { name: 'Computer Engineering', duration: '4 years', fees: 28750 },
      { name: 'Instrumentation and Control', duration: '4 years', fees: 28750 },
      { name: 'Production Engineering', duration: '4 years', fees: 28750 },
    ],
  },
  {
    name: 'RV College of Engineering',
    location: 'Bangalore, Karnataka',
    fees: 250000,
    rating: 4.35,
    placements: 92,
    description: 'A private technical institution in Bangalore widely known for its placement record in top MNCs.',
    courses: [
      { name: 'Computer Science', duration: '4 years', fees: 62500 },
      { name: 'Information Science', duration: '4 years', fees: 62500 },
      { name: 'Aerospace Engineering', duration: '4 years', fees: 62500 },
    ],
  },
  {
    name: 'PSG College of Technology',
    location: 'Coimbatore, Tamil Nadu',
    fees: 110000,
    rating: 4.3,
    placements: 88,
    description: 'An government-aided college renowned for its industry-institution interaction and strong core engineering programs.',
    courses: [
      { name: 'Computer Science', duration: '4 years', fees: 27500 },
      { name: 'Metallurgical Engineering', duration: '4 years', fees: 27500 },
      { name: 'Automobile Engineering', duration: '4 years', fees: 27500 },
    ],
  },
  {
    name: 'VJTI Mumbai',
    location: 'Mumbai, Maharashtra',
    fees: 90000,
    rating: 4.35,
    placements: 90,
    description: 'Veermata Jijabai Technological Institute is a highly competitive state-level premier institute in Mumbai.',
    courses: [
      { name: 'Computer Engineering', duration: '4 years', fees: 22500 },
      { name: 'Textile Technology', duration: '4 years', fees: 22500 },
      { name: 'Civil Engineering', duration: '4 years', fees: 22500 },
    ],
  },
  {
    name: 'Thapar Institute',
    location: 'Patiala, Punjab',
    fees: 310000,
    rating: 4.25,
    placements: 86,
    description: 'A leading private university in North India offering comprehensive engineering and management degrees.',
    courses: [
      { name: 'Computer Science', duration: '4 years', fees: 77500 },
      { name: 'Electronics and Computers', duration: '4 years', fees: 77500 },
      { name: 'Mechatronics Engineering', duration: '4 years', fees: 77500 },
    ],
  },
  {
    name: 'PEC Chandigarh',
    location: 'Chandigarh, Chandigarh',
    fees: 140000,
    rating: 4.2,
    placements: 85,
    description: 'PEC is a historic engineering college in Chandigarh with a strong alumni network.',
    courses: [
      { name: 'Aerospace Engineering', duration: '4 years', fees: 35000 },
      { name: 'Computer Science', duration: '4 years', fees: 35000 },
      { name: 'Mechanical Engineering', duration: '4 years', fees: 35000 },
    ],
  },
  {
    name: 'NSUT Delhi',
    location: 'Delhi, Delhi',
    fees: 190000,
    rating: 4.4,
    placements: 91,
    description: 'Netaji Subhas University of Technology is a highly ranked state university in Delhi.',
    courses: [
      { name: 'Computer Engineering', duration: '4 years', fees: 47500 },
      { name: 'Information Technology', duration: '4 years', fees: 47500 },
      { name: 'Instrumentation and Control', duration: '4 years', fees: 47500 },
    ],
  },
  {
    name: 'HBTU Kanpur',
    location: 'Kanpur, Uttar Pradesh',
    fees: 135000,
    rating: 4.15,
    placements: 84,
    description: 'Harcourt Butler Technical University is historic and known for its Paint and Oil Technology departments.',
    courses: [
      { name: 'Chemical Engineering', duration: '4 years', fees: 33750 },
      { name: 'Paint Technology', duration: '4 years', fees: 33750 },
      { name: 'Leather Technology', duration: '4 years', fees: 33750 },
    ],
  },
  {
    name: 'MNNIT Allahabad',
    location: 'Allahabad, Uttar Pradesh',
    fees: 140000,
    rating: 4.4,
    placements: 92,
    description: 'Motilal Nehru National Institute of Technology boasts some of the best placement percentages among NITs.',
    courses: [
      { name: 'Computer Science and Engineering', duration: '4 years', fees: 35000 },
      { name: 'Production Engineering', duration: '4 years', fees: 35000 },
      { name: 'Chemical Engineering', duration: '4 years', fees: 35000 },
    ],
  },
  {
    name: 'VNIT Nagpur',
    location: 'Nagpur, Maharashtra',
    fees: 135000,
    rating: 4.3,
    placements: 88,
    description: 'Visvesvaraya National Institute of Technology is a premier technical institute in Central India.',
    courses: [
      { name: 'Mining Engineering', duration: '4 years', fees: 33750 },
      { name: 'Computer Science', duration: '4 years', fees: 33750 },
      { name: 'Electrical Engineering', duration: '4 years', fees: 33750 },
    ],
  },
  {
    name: 'MANIT Bhopal',
    location: 'Bhopal, Madhya Pradesh',
    fees: 130000,
    rating: 4.25,
    placements: 87,
    description: 'Maulana Azad National Institute of Technology features a massive campus and strong engineering facilities.',
    courses: [
      { name: 'Planning and Architecture', duration: '5 years', fees: 26000 },
      { name: 'Computer Science', duration: '4 years', fees: 32500 },
      { name: 'Materials Science', duration: '4 years', fees: 32500 },
    ],
  },
  {
    name: 'SVNIT Surat',
    location: 'Surat, Gujarat',
    fees: 135000,
    rating: 4.3,
    placements: 88,
    description: 'Sardar Vallabhbhai National Institute of Technology is a leading NIT in Gujarat.',
    courses: [
      { name: 'Chemical Engineering', duration: '4 years', fees: 33750 },
      { name: 'Computer Engineering', duration: '4 years', fees: 33750 },
      { name: 'Civil Engineering', duration: '4 years', fees: 33750 },
    ],
  },
  {
    name: 'MNIT Jaipur',
    location: 'Jaipur, Rajasthan',
    fees: 140000,
    rating: 4.35,
    placements: 89,
    description: 'Malaviya National Institute of Technology is known for its beautiful architecture and academic rigor.',
    courses: [
      { name: 'Metallurgical Engineering', duration: '4 years', fees: 35000 },
      { name: 'Computer Science', duration: '4 years', fees: 35000 },
      { name: 'Electronics Engineering', duration: '4 years', fees: 35000 },
    ],
  },
  {
    name: 'NIT Calicut',
    location: 'Kozhikode, Kerala',
    fees: 145000,
    rating: 4.4,
    placements: 90,
    description: 'NIT Calicut is a highly-ranked National Institute of Technology located in Kerala.',
    courses: [
      { name: 'Computer Science', duration: '4 years', fees: 36250 },
      { name: 'Electrical Engineering', duration: '4 years', fees: 36250 },
      { name: 'Biotechnology', duration: '4 years', fees: 36250 },
    ],
  },
  {
    name: 'NIT Kurukshetra',
    location: 'Kurukshetra, Haryana',
    fees: 130000,
    rating: 4.3,
    placements: 88,
    description: 'NIT Kurukshetra is a premier technical institute in Haryana with good research programs.',
    courses: [
      { name: 'Computer Engineering', duration: '4 years', fees: 32500 },
      { name: 'Information Technology', duration: '4 years', fees: 32500 },
      { name: 'Production Engineering', duration: '4 years', fees: 32500 },
    ],
  },
  {
    name: 'NIT Silchar',
    location: 'Silchar, Assam',
    fees: 120000,
    rating: 4.25,
    placements: 86,
    description: 'NIT Silchar is known for its quiet, academic-friendly campus in North East India.',
    courses: [
      { name: 'Computer Science', duration: '4 years', fees: 30000 },
      { name: 'Electronics and Instrumentation', duration: '4 years', fees: 30000 },
      { name: 'Mechanical Engineering', duration: '4 years', fees: 30000 },
    ],
  },
  {
    name: 'NIT Durgapur',
    location: 'Durgapur, West Bengal',
    fees: 125000,
    rating: 4.25,
    placements: 87,
    description: 'NIT Durgapur is a highly ranked national level engineering institute in West Bengal.',
    courses: [
      { name: 'Computer Science', duration: '4 years', fees: 31250 },
      { name: 'Electrical Engineering', duration: '4 years', fees: 31250 },
      { name: 'Chemical Engineering', duration: '4 years', fees: 31250 },
    ],
  },
  {
    name: 'NIT Jalandhar',
    location: 'Jalandhar, Punjab',
    fees: 125000,
    rating: 4.2,
    placements: 85,
    description: 'NIT Jalandhar offers high-quality technical education in Punjab with modern labs.',
    courses: [
      { name: 'Computer Science', duration: '4 years', fees: 31250 },
      { name: 'Industrial Engineering', duration: '4 years', fees: 31250 },
      { name: 'Textile Technology', duration: '4 years', fees: 31250 },
    ],
  },
  {
    name: 'IIIT Delhi',
    location: 'Delhi, Delhi',
    fees: 320000,
    rating: 4.5,
    placements: 94,
    description: 'Indraprastha Institute of Information Technology Delhi is known for research in computer science.',
    courses: [
      { name: 'Computer Science', duration: '4 years', fees: 80000 },
      { name: 'Computer Science and Design', duration: '4 years', fees: 80000 },
      { name: 'Electronics Engineering', duration: '4 years', fees: 80000 },
    ],
  },
  {
    name: 'DA-IICT',
    location: 'Gandhinagar, Gujarat',
    fees: 220000,
    rating: 4.3,
    placements: 91,
    description: 'Dhirubhai Ambani Institute of Information and Communication Technology is a major center for ICT education.',
    courses: [
      { name: 'ICT Engineering', duration: '4 years', fees: 55000 },
      { name: 'ICT with minors in CS', duration: '4 years', fees: 55000 },
      { name: 'Mathematics and Computing', duration: '4 years', fees: 55000 },
    ],
  },
  {
    name: 'Nirma University',
    location: 'Ahmedabad, Gujarat',
    fees: 200000,
    rating: 4.15,
    placements: 86,
    description: 'Nirma University is a major private university in Gujarat with good placement support.',
    courses: [
      { name: 'Computer Science', duration: '4 years', fees: 50000 },
      { name: 'Chemical Engineering', duration: '4 years', fees: 50000 },
      { name: 'Electrical Engineering', duration: '4 years', fees: 50000 },
    ],
  },
  {
    name: 'KIIT University',
    location: 'Bhubaneswar, Odisha',
    fees: 300000,
    rating: 4.2,
    placements: 89,
    description: 'Kalinga Institute of Industrial Technology is a massive private university with great placements.',
    courses: [
      { name: 'Computer Science', duration: '4 years', fees: 75000 },
      { name: 'Information Technology', duration: '4 years', fees: 75000 },
      { name: 'Electronics and Communication', duration: '4 years', fees: 75000 },
    ],
  },
  {
    name: 'LPU Jalandhar',
    location: 'Phagwara, Punjab',
    fees: 180000,
    rating: 4.0,
    placements: 82,
    description: 'Lovely Professional University is a massive private campus in Punjab with global tie-ups.',
    courses: [
      { name: 'Computer Science', duration: '4 years', fees: 45000 },
      { name: 'Information Technology', duration: '4 years', fees: 45000 },
      { name: 'Mechanical Engineering', duration: '4 years', fees: 45000 },
    ],
  },
  {
    name: 'Amity University',
    location: 'Noida, Uttar Pradesh',
    fees: 280000,
    rating: 4.1,
    placements: 84,
    description: 'Amity University Noida features high-tech infrastructure and strong industry connections.',
    courses: [
      { name: 'Computer Science', duration: '4 years', fees: 70000 },
      { name: 'Biotechnology', duration: '4 years', fees: 70000 },
      { name: 'Electronics Engineering', duration: '4 years', fees: 70000 },
    ],
  },
];

async function main() {
  console.log('Start seeding...');
  
  // Clear existing data to avoid unique constraint violations
  await prisma.course.deleteMany({});
  await prisma.college.deleteMany({});
  
  for (const collegeData of collegesData) {
    const { courses, ...collegePart } = collegeData;
    
    const college = await prisma.college.upsert({
      where: { name: collegePart.name },
      update: {},
      create: {
        ...collegePart,
        courses: {
          create: courses,
        },
      },
    });
    
    console.log(`Created college with id: ${college.id}`);
  }
  
  console.log('Seeding finished.');
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
